FROM nginx:latest

# Copia los archivos de configuración a la imagen
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY certificate.pem /etc/ssl/certs/certificate.pem
COPY key.pem /etc/ssl/certs/key.pem