apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
data:
  PASSWD_REDIS: YTk3ZjdhN2MzYzcxMDFkOWQxNWM1NWU2ZmJhOGEyYmYzOTNiZjA1NDg5YWNlNzkwZjg2MDY0MTQ2NjhkNTM4Yw==
